require 'sinatra'
require 'sinatra/activerecord'
require 'bcrypt'
require 'byebug'
require_relative 'models/user'
require_relative 'models/tweet'
require_relative 'models/comment'
require_relative 'models/follow'
require_relative 'models/hash_tag'
require_relative 'models/like'
require_relative 'models/mention'
require_relative 'controllers/tweet'
require_relative 'controllers/user'

