source 'https://rubygems.org'

gem 'activerecord'
gem 'activerecord-import'
gem 'bcrypt'
gem 'faker'
gem 'irb'
gem 'minitest'
gem 'pg', '~> 0.18'
gem 'pry-byebug'
gem 'rack'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
