source 'https://rubygems.org'
gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg', '~> 0.18'
gem 'pry-byebug'
gem 'rake'
gem 'faker'
gem 'bcrypt'
gem 'activerecord-import'
gem 'sinatra-contrib'
gem 'irb'
