branch-defaults:
  '0.2':
    environment: Nanotwitter-env
environment-defaults:
  Nanotwitter-env:
    branch: null
    repository: null
global:
  application_name: nanotwitter
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.6
    running on 64bit Amazon Linux/2.9.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
