development:
  adapter: postgresql
  encoding: unicode
  database: nt_dev_db
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: nt_test_db
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: nt_prod_db
  pool: 2
  username: your_username
  password: your_password