development:
  adapter: postgresql
  encoding: unicode
  database: nt_dev_db
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: nt_test_db
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  pool: 2
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
