# These params are passsed to the corresponding aws-sdk ecs client methods.
# AWS Docs example: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECS/Client.html#run_task-instance_method
#
# The network helper provides access to the .ufo/settings/network/[PROFILE].yml
#
# More docs: http://ufoships.com/docs/params/

# ufo task calls run_tasks.
#
# ufo task will assign these values appropriately based on the task
# definition being ran. So generally you should you can leave these settings
# alone.
#
# If it's a Fargate task definition, ufo task automatically adds the
# network_configuration and launch_type: FARGATE
# If it's a EC2 task definition with awsvpc network mode, ufo task
# automatically adds the network_configuration and security groups using
# the security groups from .ufo/settings/network/default.yml.
#
# run_task:
#   # network_configuration is required for FARGATE
#   network_configuration:
#     awsvpc_configuration:
#       subnets: <%= network[:ecs_subnets].inspect %> # required
#       security_groups: <%= network[:ecs_security_groups].inspect %>
#       # for fargate use: assign_public_ip: ENABLED
#       # assign_public_ip: ENABLED # accepts ENABLED, DISABLED
